# Generated by Django 5.0.6 on 2024-05-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('raiting', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'w trakcie pisania'), (2, 'czeka na akceptacje'), (3, 'opublikowany')])),
                ('start_emission', models.DateField(null=True)),
                ('end_emission', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('still_active', models.BooleanField(default=True)),
                ('genre', models.IntegerField(choices=[(-1, 'Not Define'), (0, 'rock'), (1, 'metal'), (2, 'pop'), (3, 'hio hop'), (4, 'electronic'), (5, 'reggae'), (6, 'other')])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
